resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/3.yaml

packages:
- .
nix:
  packages: [glew, dcraw, enblend-enfuse, hugin, imagemagick, fgallery, sxiv, libffi, exiftool]
